get http://localhost:3000/a_movie_query/2

###

POST http://localhost:3000/actor_by_body
Content-Type: application/json

{
  "name": "Tony"
}

###

GET http://localhost:3000/actor_query/5


###


GET http://localhost:3000/actor_by_url/5 
