@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDM0MzAxMjh9.LIofWgB0eGsh23OWHxHWqLwQiOad8rUmi8Emb4ylhEE

##START MOVIES PATHING
#index
Get http://localhost:3000/movies

###
#show
Get http://localhost:3000/movies/3

###
#create
POST http://localhost:3000/movies
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{

   "title": "Blade",
   "year": "1998",
   "plot": "In the film, Blade is a Dhampir, a human with vampire strengths but not their weaknesses, who together with his mentor Abraham Whistler and hematologist Karen Jenson, fights against vampires, namely the exceptionally vicious Deacon Frost.",
   "director": "Stephen Norrington",
   "english": true

}

###
#update

Patch http://localhost:3000/movies/1
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  
  "title": "The_Matrix",
  "year": "1999",
  "plot": "depicts a dystopian future in which humanity is unknowingly trapped inside a simulated reality, the Matrix, which intelligent machines have created to distract humans while using their bodies as an energy source.",
  "director": "The Wichowskis",
  "english": true

}

###
#delete
DELETE http://localhost:3000/movies/2


###
#START ACTORS PATHING
#create
POST http://localhost:3000/actors
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{

  "first_name": "Wesley",
  "last_name": "Snipes",
  "known_for": "Blade",
  "gender": "male",
  "age": 59,
  "movie_id": 7

}


###
#show
GET http://localhost:3000/actors/5

###
#index
GET http://localhost:3000/actors 


###
#update

PATCH http://localhost:3000/actors/5
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{

"first_name": "Tony",
"last_name": "Jaa",
"known_for": "Ong_Bak",
"gender": "Male",
"age": 45,
"movie_id": 3

}

###
#destroy
DELETE http://localhost:3000/actors/10


###USERS 
#Create user (sign_up)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name":"Tom",
  "email":"Tom@gmail.com",
  "password":"password",
  "password_confirmation":"password",
  "admin": true
}

###SESSIONS
#Create session (login)
POST http://localhost:3000/sessions
Content-Type: application/json


{
  "email": "Tom@gmail.com",
  "password": "password"
}


#####MOVIE_GENRES
#CREATE GENRE
POST http://localhost:3000/movie_genres
Content-Type: application/json

{
  "genre_id":1 ,
  "movie_id":3
}

###
#INDEX
GET http://localhost:3000/movie_genres