##START MOVIES PATHING
#index
Get http://localhost:3000/movies

###
#show
Get http://localhost:3000/movies/3

###
#create
POST http://localhost:3000/movies
Content-Type: application/json

{

   "title": "Blade",
   "year": "1998",
   "plot": "In the film, Blade is a Dhampir, a human with vampire strengths but not their weaknesses, who together with his mentor Abraham Whistler and hematologist Karen Jenson, fights against vampires, namely the exceptionally vicious Deacon Frost.",
   "director": "Stephen Norrington",
   "english": true

}

###
#update

Patch http://localhost:3000/movies/1
Content-Type: application/json

{
  
  "title": "The_Matrix",
  "year": "1999",
  "plot": "depicts a dystopian future in which humanity is unknowingly trapped inside a simulated reality, the Matrix, which intelligent machines have created to distract humans while using their bodies as an energy source.",
  "director": "The Wichowskis",
  "english": true

}

###
#delete
DELETE http://localhost:3000/movies/2

###
#START ACTORS PATHING
#create
POST http://localhost:3000/actors
Content-Type: application/json

{

  "first_name": "Wesley",
  "last_name": "Snipes",
  "known_for": "Blade",
  "gender": "male",
  "age": 59

}


###
#show
GET http://localhost:3000/actors/5

###
#index
GET http://localhost:3000/actors 


###
#update

PATCH http://localhost:3000/actors/5
Content-Type: application/json

{

"first_name": "Tony",
"last_name": "Jaa",
"known_for": "Ong_Bak",
"gender": "Male",
"age": 45

}

###
#destroy
DELETE http://localhost:3000/actors/10